- name: stop postgres
  service:
    name: postgresql 
    state: stopped
  become: True
- name: remove pg data
  file: 
    path: "{{ pg_data_dir }}*" 
    state: absent
  become: True
- name: cloning db
  command: repmgr -h {{ hostvars[groups['primary'][0]].local_ip }} -U repmgr -d repmgr -f {{ repmgr_config }} standby clone -F
  become: True
  become_user: postgres
- name: start postgres
  service:
    name: postgresql 
    state: started
  become: True
- name: register standby
  command: repmgr -f {{ repmgr_config }} standby register --force
  register: repmgr_log
  become: True
  become_user: postgres
  notify:
    - save repmgr log
