database_port: 5432
pg_version: 12
pg_apt_key: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
pg_apt_repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
